### ISSUE TITLE
BayesianMixtures update for version >=1?

### ISSUE THREAD

**Issue by cmerkatas** [jwmi/BayesianMixtures.jl#4]
Hi @jwmi!

Thank you for the package, it seems very interesting. However, I tried to install it on Julia 1.0.0
but it doesn't seem to be updated.

Is there going to be an update for later versions of Julia?

Cheers,
Christos

**Comment by jwmi** [comment]
Hi @cmerkatas!

Thanks for the comment and sorry for the very delayed reply.  Yes, I need to update the package to work with Julia >=1.  Hoping to get to this sometime soon.

All the best,
Jeff

**Comment by cmerkatas** [comment]
Hi @jwmi,

Thank you very much for your reply.

All the best,
Christos

**Comment by jwmi** [comment]
Hi @cmerkatas ,
Just wanted to let you know that the code has now been updated to work with the current Julia version.
Best,
Jeff

**Comment by cmerkatas** [comment]
Hi @jwmi! Thank you for the update!

Best
Christos
